#!/bin/sh

for s; do
  s=$(basename "$s") &&
  for i in "$s"/??.mdwn; do
    t=$(grep '^\[\[!meta title' | cut -d \" -f 2) \
      < "$i" &&
    i=$(expr "$i" : '\(.*\)\.mdwn') &&
    cat \
      > "$t".mdwn \
      <<EOF
[[!meta copyright="Copyright © 2009 Free Software Foundation, Inc."]]

[[!meta license="""[[!toggle id="license" text="GFDL 1.2+"]][[!toggleable
id="license" text="Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no Invariant
Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of the license
is included in the section entitled [[GNU Free Documentation
License|/fdl]]."]]"""]]

[[!meta redir=$i]]
EOF
  done
done
