#!/bin/sh

# Mangle the rendered files to cause fewer differernces upon re-rendering.

# Written by Thomas Schwinge <tschwinge@gnu.org>.

# Un-mangle mailto links: convert HTML character entities to real characters.
find ./ -name \*.html -print0 \
  | xargs -0 \
    perl -p -i -l -e \
      'BEGIN { $replacing = 0; }
      # The replacing-toggling logic is a bit rough, but so is life.
      $replacing = 1 if /<a href="mailto:/;
      s%\&#(x?)([^;]*);%chr(length($1) ? hex($2) : $2)%eg if $replacing;
      $replacing = 0 if /<\/a>/;'
