#!/bin/sh

# Render the pages of this repository.

# Written by Thomas Schwinge <tschwinge@gnu.org>

export ROOT && ROOT=$(readlink -f "$(dirname "$0")") &&

case $1 in
  --official)
    # Use this for rendering the set of pages which are to be installed under
    # <http://www.gnu.org/software/hurd/>.
    shift &&
    export TZ && TZ=UTC &&
    export DESTDIR && DESTDIR=$ROOT.rendered.official &&
    set x \
      --set wikistatedir="$ROOT"/.ikiwiki-official \
      "$@" &&
    shift;;
  *)
    # Use ``--no-usedirs'' here, because when browsing local files, the web
    # browsers don't display `index.html' files by default when a hyperlink
    # referencing a directory is being opened.
    set x \
      --no-usedirs \
      "$@" &&
    shift;;
esac &&

ikiwiki \
  --setup "$ROOT"/ikiwiki.setup \
  --refresh \
  "$@" &&

echo &&
echo Now\ open\ \`"${DESTDIR-"$ROOT".rendered}"/index.html\'' to browse the web pages.'
