#!/bin/sh

# Render the pages of this repository for your local browsing pleasure.

# We use ``--no-usedirs'' here, because when browsing local files, the web
# browsers don't display `index.html' files by default when a hyperlink
# referencing a directory is being opened.

# Written by Thomas Schwinge <tschwinge@gnu.org>


src=$(dirname "$0") &&
# Invoking ikiwiki with ``src=.'' will make it render `.git/' as well.
if [ "$src" = . ]
then src=$(pwd)
else :
fi &&
dest=$src.rendered &&

ikiwiki \
  --verbose \
  --wikiname GNU\ Hurd\ wiki \
  --userdir user \
  --no-usedirs \
  "$src" "$dest" &&

echo &&
echo Now\ open\ \`"$dest"/index.html\'' to browse the wiki pages.'
