#!/bin/sh

# merge into master  
git checkout master  
git pull --rebase  
git merge master-news_next

# push master  
git push origin master

# switch back to master-news_next  
git checkout master-news_next  
git pull --rebase
